### ISSUE TITLE
Config to use PostgreSQL instead of mysql

### ISSUE THREAD

**Issue by renatolond** [open-eats/openeats-api#17]
I'm setting up openeats and I use PostgreSQL for other projects in my servers already and would prefer to use it instead of MySQL. I configured it instead of MySQL and it seems to work so far on my dev env. Would you be interested in being able to choose between the two?

**Comment by RyanNoelk** [comment]
More options are always better. I don't think OpenEats will ever need to use an special DB settings. Please open a pull request If you have something. Otherwise we can discuss more here.

Thanks,
-Ryan

**Comment by renatolond** [comment]
I did a quick change to just get it working, here: https://github.com/renatolond/openeats-api/commit/22d1cb932843f68fb02b395d331ba55968e5fc48
But ideally I think it would be better to have something more like
```
if USE_POSTGRES:
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
```

And then maybe for the existing ENV variables, to avoid breaking existing apps something like

```
os.environ.get('DATABASE_NAME', os.environ.get('MYSQL_DATABASE', 'openeats'))
```

The OPTIONS part I don't know what's the best way to deal with :thinking:

**Comment by RyanNoelk** [comment]
I'm less worried about the settings file than I am about the requirements file. Your commit reminded me that we need different dependencies for postgres and mysql.

The setting's file can just contain a separate block for the DATABASES.

```
if postgres:
    DATABASES = [...postgres]
else:
    DATABASES = [...mysql]
```

The tricky part is making it work without having the overhead from the extra deps. I'll think on this.

**Comment by RyanNoelk** [comment]
So I don't think that I'm going to include this. Having multiple supported DBs in the docker image doesn't seem very clean. you are free to keep suing what you have.

Going to close this for now. If I get a better idea I will reopen.
