### ISSUE TITLE
"Authentication credentials were not provided."

### ISSUE THREAD

**Issue by mab5vot9us9a** [open-eats/openeats-api#22]
After creating a token under `/admin/authtoken/token/`, I wanted to try the [example curl command](https://openeats.readthedocs.io/en/latest/Dev_tips/) and including the previously generated token I still get "Authentication credentials were not provided.".

Following command gets executed:

```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Token 1bafd426f202347e51sd79fd8a7932d617e4d503" https://my.domain.com/api/v1/recipe/recipes/ --data '{"info":"hi", "cook_time":"12", "title":"hi", "directions":[{"title":"do this first", "step":"1"}], "servings":"12", "cuisine":"1", "ingredients":[{"title":"first", "quantity":"2", "measurement":"tsp"}], "prep_time":"123", "course":"1", "tags":[{"author":"1", "title":"chicken"}]}'
```

**Comment by RyanNoelk** [comment]
This request is quite old. I should remove it from the docs as the UI is best way to go about creating a recipe ATM.

**Comment by mab5vot9us9a** [comment]
oh, I see :( I was hoping to add some scraped recipes.

**Comment by RyanNoelk** [comment]
If u are looking for a way to add a recipe directly through the UI, then you should look at the request that the UI is sending. The API uses JWT to authenticate so you can use your own token for a recipe scraper.
