### ISSUE TITLE
Unable to create new recipes using API 

### ISSUE THREAD

**Issue by dxsh** [open-eats/openeats-api#23]
I'm attempting to use the API to create new recipes, however it's not working for some odd reason. I'm logging in and getting the JWT token, and setting the Authorization header. I'm copying the raw request body from a recipe I created manually in my browser. The request returns 200, however no recipe is created.

        url = "http://REDACTED/api/v1/recipe/recipes"
        data = {"id":3,"slug":"","public":"true","errors":{"course":"","cuisine":"","prep_time":"","cook_time":"","title":"","info":"","ingredient_groups":"","directions":"","servings":""},"course":{"id":3,"title":"Frukost"},"cuisine":{"id":3,"title":"Vegan"},"prep_time":"2","cook_time":"1","title":"test2","info":"test","ingredient_groups":[{"title":"","ingredients":[{"title":"test"}]}],"directions":"test","servings":"1"}
        
        token = login()
        headers = {"Content-Type": "application/json", "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0", "Authorization": "JWT " + token}
        req = session.post(url, json=data, headers=headers)
    

What am I missing here?

**Comment by RyanNoelk** [comment]
Well that is really strange. I can't see a reason why that wouldn't work. I'll investigate it.

In the meantime can you give me a little more info and answer a few questions for me:
- If you go to the admin panel (http://REDACTED/admin -> click on recipes) can you view your recipe there?
- If no to the above can you see the recipe in the database? (``)
